= Job과 CronJob
include::vars.adoc[]
include::_attributes.adoc[]
:watch-terminal: 터미널 2

대부분의 경우, 쿠버네티스는 들어오는 요청에 대한 응답을 처리하는 것이 목적인 "장기" 프로세스를 실행하는 플랫폼으로 사용됩니다.

하지만 쿠버네티스는 어떤 로직(예: 데이터베이스 업데이트, 배치 처리 등)을 실행하고 종료되는 것이 목적인 프로세스도 실행할 수 있게 해줍니다.

쿠버네티스 Job은 어떤 로직을 한 번 실행하는 작업입니다.

쿠버네티스 CronJob은 Cron 패턴에 따라 반복되는 Job입니다.

== 준비

=== 네임스페이스 설정

올바른 네임스페이스에 있는지 확인합니다:

:section-k8s: resource
:set-namespace: myspace

include::partial$new-terminal.adoc[]

=== 터미널 지켜보기

어떤 일이 벌어지는지 관찰할 수 있도록, 다른 터미널(**{watch-terminal}**)을 열어서 여러 job을 실행하는 동안 발생하는 일을 ``watch``해 봅시다.

:section-k8s: cronjobs

include::partial$watching-pods-with-nodes.adoc[]

== Job

:quick-open-file: whalesay-job.yaml

Job은 쿠버네티스의 `Job` 리소스를 사용해서 생성합니다. 하나를 살펴보기 위해 ``{quick-open-file}``을 열어 보세요. 이 파일에서 눈여겨볼 부분은 다음과 같습니다:

[source, yaml]
.{quick-open-file}
----
include::example$whalesay-job.yaml[]
----
<.> job의 이름은 이 job 정의로부터 생성되는 모든 pod에 `job-name` 레이블의 값으로 사용됩니다.

[tabs]
====
터미널 1::
+
--
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
cat <<EOF | oc apply -f -
apiVersion: batch/v1
kind: Job
metadata:
  name: whale-say-job 
spec:
  template:
    spec:
      containers:
      - name: whale-say-container
        image: docker/whalesay
        command: ["cowsay","Hello DevNation"]
      restartPolicy: Never
EOF
----
--
====

그러면 **{watch-terminal}**에서 (연속적으로 갱신되며) 다음과 같은 출력을 얻게 됩니다.

[tabs]
====
{watch-terminal}::
+
--
[.console-output]
[source,bash]
----
NAME                 READY  STATUS             AGE  NODE
whale-say-job-m8vxt  0/1    ContainerCreating  14s  devnation-m02
----

[.console-output]
[source,bash]
----
NAME                 READY  STATUS     AGE  NODE
whale-say-job-m8vxt  1/1    Running    80s  devnation-m02
----

[.console-output]
[source,bash]
----
NAME                 READY  STATUS     AGE  NODE
whale-say-job-m8vxt  0/1    Completed  85s  devnation-m02
----
--
====


다른 쿠버네티스 리소스와 마찬가지로 ``job``을 조회할 수 있습니다:

[tabs]
====
터미널 1::
+
--
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
oc get jobs
----

[.console-output]
[source,bash]
----
NAME            COMPLETIONS   DURATION   AGE
whale-say-job   1/1           20s        36s
----
--
====

job은 pod에 의해 실행되므로, `job` 실행 결과를 확인하려면 그 pod의 로그만 조회하면 됩니다:

[.console-input]
[source,bash,subs="+macros,+attributes"]
----
oc logs \
  -l job-name=whale-say-job \#<.>
  --tail=-1 #<.>
----
<.> 이렇게 하면 `job-name` 레이블(위 참고)이 ``whale-say-job``으로 설정된 모든 pod를 찾을 수 있습니다.
<.> ``--tail``은 로그 명령이 (pod) 로그의 끝에서부터 몇 줄을 반환할지 지정합니다. 이 job pod 메시지의 재미있는 부분을 모두 볼 수 있도록 ``-1``로 설정해서 모든 줄을 확인합니다footnote:[일반적으로 --tail의 기본값은 -1이지만, 이는 __단일한 특정 리소스__에서 로그를 요청할 때만 해당됩니다. (지금처럼 레이블로 로그를 요청할 때처럼) 여러 리소스의 로그가 반환될 가능성이 있는 경우에는, 각 리소스의 로그에서 반환되는 줄 수가 기본적으로 10줄로 제한됩니다]

[.console-output]
[source,bash]
----
 _________________
< Hello DevNation >
 -----------------
    \
     \
      \
                    ##        .
              ## ## ##       ==
           ## ## ## ##      ===
       /""""""""""""""""___/ ===
  ~~~ {~~ ~~~~ ~~~ ~~~~ ~~ ~ /  ===- ~~~
       \______ o          __/
        \    \        __/
          \____\______/
----

=== 정리

[tabs]
====
터미널 1::
+
--
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
cat <<EOF | oc delete -f -
apiVersion: batch/v1
kind: Job
metadata:
  name: whale-say-job 
spec:
  template:
    spec:
      containers:
      - name: whale-say-container
        image: docker/whalesay
        command: ["cowsay","Hello DevNation"]
      restartPolicy: Never
EOF
----
--
====


== CronJob

:quick-open-file: whalesay-cronjob.yaml

CronJob은 쿠버네티스의 `CronJob` 리소스를 사용해서 정의합니다. ``cronjob``이라는 이름은 리눅스에서 유래한 것으로, 한 번 또는 반복적으로 실행되도록 예약된 일종의 배치 프로세스를 나타냅니다. 이 개념이 쿠버네티스에서는 `{quick-open-file}` 파일에서 볼 수 있듯이 다음과 같이 구현됩니다:

[source, yaml]
.{quick-open-file}
----
include::example$whalesay-cronjob.yaml[]
----
<.> 이 문자열은 job이 매분 실행됨을 나타냅니다.
<.> 여기서는 ``cronjob``이 생성하는 ``job``과 ``pod``에 적용하고 싶은 우리만의 추가 레이블을 지정합니다. `job-name` 레이블은 여전히 존재하지만, 매번 guid를 포함하게 되어 그 값을 미리 예측할 수는 없습니다.

[tabs]
====
터미널 1::
+
--
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
cat <<EOF | oc apply -f -
apiVersion: batch/v1
kind: CronJob
metadata:
  name: whale-say-cronjob
spec:
  schedule: "* * * * *" 
  jobTemplate:                   
    spec:                        
      template:    
        metadata:
          labels:
            job-type: whale-say #<.>              
        spec:
          containers:
          - name: whale-say-container
            image: docker/whalesay
            command: ["cowsay","Hello DevNation"]
          restartPolicy: Never
EOF
----
--
====

그런 다음 **{watch-terminal}**의 watch 창을 살펴보면

[tabs]
====
{watch-terminal}::
+
--
[.console-output]
[source,bash]
----
NAME                  READY   STATUS      RESTARTS   AGE
----

--
====

CronJob이 준비되는 동안이라 실행 중인 Pod가 없습니다(그리고 대략 10초에 한 번씩만 확인됩니다. 아래 경고를 참고하세요).

cronjob이 실행되기를 기다리는 동안, **터미널 1**을 사용해서 ``cronjob``이 어떻게 변하는지 지켜볼 수 있습니다:

[tabs]
====
터미널 1::
+
--
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
oc get cronjobs -w #<.>
----
<.> `-w` 플래그는 출력을 지켜보라는 의미입니다(**{watch-terminal}**에서 하고 있는 것과 비슷하게요), 다만 관찰 대상 리소스(여기서는 `cronjob`)의 상태가 바뀔 때만 새로 출력됩니다.

거의 3분을 기다린 후의 대표적인 출력은 다음과 같습니다(job이 재시작되는 것에 주목하세요):

[.console-output]
[source,bash,subs="+macros,+attributes,+quotes"]
----
NAME                SCHEDULE      SUSPEND   ACTIVE   LAST SCHEDULE   AGE
whale-say-cronjob   * * * * *   False     #1#        0s              #20s# #<.>
whale-say-cronjob   * * * * *   False     0        31s             51s
whale-say-cronjob   * * * * *   False     #1#        0s              #80s# #<.>
whale-say-cronjob   * * * * *   False     0        23s             103s
whale-say-cronjob   * * * * *   False     #1#        1s              #2m21s#
----
<.> 첫 번째 실행은 시작하기까지 시간이 좀 걸렸는데, 이는 `cronjob` 스케줄과는 무관합니다.
<.> 다음 job이 활성화되는 시점이 첫 번째 job이 활성화된 시점(AGE 기준)으로부터 약 60초 뒤라는 점에 주목하세요. 그리고 그다음 job도 그로부터 약 60초 뒤의 AGE를 갖습니다.
--
====

cronjob이 ACTIVE로 바뀔 때마다(위의 강조 표시 참고) **{watch-terminal}**에서 다음과 같은 내용을 보게 될 것입니다:

[tabs]
====
{watch-terminal}::
+
--
[.console-output]
[source,bash]
----
NAME                              READY  STATUS     AGE  NODE
whale-say-cronjob-27108480-2ws6k  0/1    Completed  46s  devnation-m02
----
--
====

[WARNING]
====
link:https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/[쿠버네티스 공식 문서]에 따르면: cron job은 스케줄의 실행 시각마다 대략 한 번씩 job 객체를 생성합니다. "대략"이라고 하는 이유는 특정 상황에서는 두 개의 job이 생성되거나, 하나도 생성되지 않을 수도 있기 때문입니다. 이런 경우는 드물게 만들려고 노력하지만 완전히 막지는 못합니다. 따라서 job은 멱등적이어야 합니다.
====

`describe` 서브커맨드를 사용해서 cronjob을 살펴봅시다. kbd:[CTRL+c]를 눌러 `oc get cronjobs -w` 명령을 취소하고 다음 명령으로 대체하세요:


[.console-input]
[source,bash,subs="+macros,+attributes"]
----
oc describe cronjobs
----

그러면 다음과 비슷한 내용을 볼 수 있습니다.

[.console-output]
[source,bash,subs="+quotes"]
----
Name:                          whale-say-cronjob
Namespace:                     myspace
Labels:                        <none>
Annotations:                   <none>
Schedule:                      * * * * *
Concurrency Policy:            Allow
Suspend:                       False
#Successful Job History Limit:  3# #<.>
Failed Job History Limit:      1
Starting Deadline Seconds:     <unset>
Selector:                      <unset>
Parallelism:                   <unset>
Completions:                   <unset>
Pod Template:
  Labels:  #job-type=whale-say#
  Containers:
   whale-say-container:
    Image:      docker/whalesay
    Port:       <none>
    Host Port:  <none>
    Command:
      cowsay
      Hello DevNation
    Environment:     <none>
    Mounts:          <none>
  Volumes:           <none>
#Last Schedule Time:  Sat, 17 Jul 2021 08:06:00 +0000# #<.>
Active Jobs:         whale-say-cronjob-27108486
Events:
  Type    Reason            Age    From                Message
  ----    ------            ----   ----                -------
  Normal  SuccessfulCreate  6m21s  cronjob-controller  Created job whale-say-cronjob-27108480
  Normal  SawCompletedJob   6m1s   cronjob-controller  Saw completed job: whale-say-cronjob-27108480, status: Complete
  Normal  SuccessfulCreate  5m21s  cronjob-controller  Created job whale-say-cronjob-27108481
  Normal  SawCompletedJob   4m56s  cronjob-controller  Saw completed job: whale-say-cronjob-27108481, status: Complete
  Normal  SuccessfulCreate  4m21s  cronjob-controller  Created job whale-say-cronjob-27108482
  Normal  SawCompletedJob   3m56s  cronjob-controller  Saw completed job: whale-say-cronjob-27108482, status: Complete
  Normal  SuccessfulCreate  3m21s  cronjob-controller  Created job whale-say-cronjob-27108483
  Normal  SawCompletedJob   2m48s  cronjob-controller  Saw completed job: whale-say-cronjob-27108483, status: Complete
  Normal  SuccessfulDelete  2m46s  cronjob-controller  Deleted job whale-say-cronjob-27108480
  Normal  SuccessfulCreate  2m20s  cronjob-controller  Created job whale-say-cronjob-27108484
  Normal  SawCompletedJob   104s   cronjob-controller  Saw completed job: whale-say-cronjob-27108484, status: Complete
  Normal  SuccessfulDelete  101s   cronjob-controller  Deleted job whale-say-cronjob-27108481
  Normal  SuccessfulCreate  81s    cronjob-controller  Created job whale-say-cronjob-27108485
  Normal  SawCompletedJob   54s    cronjob-controller  Saw completed job: whale-say-cronjob-27108485, status: Complete
  Normal  SuccessfulDelete  52s    cronjob-controller  Deleted job whale-say-cronjob-27108482
  Normal  SuccessfulCreate  21s    cronjob-controller  Created job whale-say-cronjob-27108486
  Normal  SawCompletedJob   1s     cronjob-controller  Saw completed job: whale-say-cronjob-27108486, status: Complete
----
<.> 쿠버네티스는 일정 시간이 지나면 job을 정리합니다.
<.> __Last Schedule Time__은 job이 마지막으로 실행된 시각을 보여준다는 점에 주목하세요.

CronJob은 스케줄이 활성화될 때마다 ``job``을 생성하고(그 job이 다시 pod를 생성) 한다는 점을 알아두는 것이 중요합니다:

[tabs]
====
터미널 1::
+
--
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
oc get jobs
----

cronjob이 3분 넘게 실행된 후의 예시 출력:

[.console-output]
[source,bash]
----
NAME                         COMPLETIONS   DURATION   AGE
whale-say-cronjob-27108487   1/1           19s        2m37s
whale-say-cronjob-27108488   1/1           20s        97s
whale-say-cronjob-27108489   1/1           21s        37s
----
--
====

마지막으로, 모든 job의 로그를 확인해서 job history의 효과를 볼 수 있습니다.

[tabs]
====
터미널 1::
+
--
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
oc logs \
  -l job-type=whale-say \#<.>
  --tail=-1
----
<.> 이번에는 `job-type` 레이블(위에서 지정한 우리만의 커스텀 레이블)이 ``whale``로 설정된 모든 것의 로그를 확인합니다.

.NOTE
****
덜 구체적이긴 하지만, __커스텀 레이블 없이도__, 다음과 같이 __레이블 값을 매칭하지 않는 방식으로__ whale job 로그를 찾아볼 __수도__ 있습니다:

[.console-input]
[source,bash,subs="+macros,+attributes,+quotes"]
----
oc logs #-l job-name# --tail=-1
----

이는 기본적으로 ``job-name``이라는 레이블을 가진 모든 pod를 매칭하라는 의미입니다.

****

[.console-output]
[source,bash]
----
 _________________ 
< Hello DevNation >
 ----------------- 
    \
     \
      \     
                    ##        .            
              ## ## ##       ==            
           ## ## ## ##      ===            
       /""""""""""""""""___/ ===        
  ~~~ {~~ ~~~~ ~~~ ~~~~ ~~ ~ /  ===- ~~~   
       \______ o          __/            
        \    \        __/             
          \____\______/   
 _________________ 
< Hello DevNation >
 ----------------- 
    \
     \
      \     
                    ##        .            
              ## ## ##       ==            
           ## ## ## ##      ===            
       /""""""""""""""""___/ ===        
  ~~~ {~~ ~~~~ ~~~ ~~~~ ~~ ~ /  ===- ~~~   
       \______ o          __/            
        \    \        __/             
          \____\______/   
 _________________ 
< Hello DevNation >
 ----------------- 
    \
     \
      \     
                    ##        .            
              ## ## ##       ==            
           ## ## ## ##      ===            
       /""""""""""""""""___/ ===        
  ~~~ {~~ ~~~~ ~~~ ~~~~ ~~ ~ /  ===- ~~~   
       \______ o          __/            
        \    \        __/             
          \____\______/   
----
--
====

=== 정리

[tabs]
====
터미널 1::
+
--
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
cat <<EOF | oc delete -f -
apiVersion: batch/v1
kind: CronJob
metadata:
  name: whale-say-cronjob
spec:
  schedule: "* * * * *" 
  jobTemplate:                   
    spec:                        
      template:    
        metadata:
          labels:
            job-type: whale-say #<.>              
        spec:
          containers:
          - name: whale-say-container
            image: docker/whalesay
            command: ["cowsay","Hello DevNation"]
          restartPolicy: Never
EOF
----
--
====
