= Secret
include::_attributes.adoc[]
:watch-terminal: 터미널 2

Secret은 쿠버네티스가 기본으로 제공하는, 민감한 데이터를 저장하는 방법입니다. config map과 가장 비슷하지만, 쿠버네티스 내부에서는 조금 더 세심하게 다뤄집니다.

Secret은 개발자가 컨테이너화된 애플리케이션의 코드(애플리케이션이든 인프라든)에 (안전하지 않게) 포함시키지 않고도 흔히 쓰이는 민감한 데이터(basic-auth 자격 증명, 이미지 레지스트리 자격 증명, TLS 인증서 등)를 지정할 수 있는 방법을 제공하기 위한 것입니다. 흔히 접하게 되는 대표적인 일반 secret은 데이터베이스 접근을 위한 자격 증명입니다.

secret의 핵심 값은 기본적으로 평문으로 표시되지 않습니다. 대신 secret 데이터는 base64로 인코딩되어 있으며, 읽으려면 디코딩해야 합니다.

[WARNING]
====
쿠버네티스 API의 대부분의 데이터와 마찬가지로, secret도 `etc` 분산 데이터 저장소 안에 저장됩니다. 이 데이터에 대한 접근은 클러스터의 RBAC로 제어되지만, 쿠버네티스에서는 기본적으로 ``etcd``에 저장된 Secret이 저장 시점에 암호화되지 **않는다**는 점에 유의해야 합니다. 일반 쿠버네티스에서는 link:https://kubernetes.io/docs/tasks/administer-cluster/encrypt-data/[다음 안내^]를 따라 이를 활성화할 수 있습니다. OpenShift에서는 link:https://docs.openshift.com/container-platform/4.7/security/encrypting-etcd.html[여기^]에 문서화된 대로 이 작업이 훨씬 더 쉽습니다.
====

== 사전 준비

올바른 네임스페이스에 있는지 확인합니다:

:section-k8s: resource
:set-namespace: {user}-myspace

include::partial$namespace-setup-tip.adoc[]

include::partial$set-context.adoc[]

네임스페이스에 아무것도 실행 중이지 않은지 확인합니다:

[#no-resources-resource]
[.console-input]
[source, bash]
----
kubectl get all
----

[.console-output]
[source,bash]
----
No resources found in myspace namespace.
----

`myboot` service를 배포합니다:

[#deploy-myboot-secrets]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
kubectl apply -f apps/kubefiles/myboot-deployment.yml
----

myboot Service를 배포합니다:

[#service-myboot-secrets]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
kubectl apply -f apps/kubefiles/myboot-service.yml
----

별도의 터미널(앞으로 **{watch-terminal}**라고 부르겠습니다)에서 pod에 대한 watch를 설정합니다:

:section-k8s: secrets
include::partial$watching-pods-with-nodes.adoc[]

한편, 메인 터미널에서 요청을 보냅니다:

:service-exposed: myboot
include::partial$env-curl.adoc[]

이제는 익숙해진 응답을 받게 될 것입니다.

[.console-output]
[source,bash,subs="+macros,+attributes"]
----
Aloha from Spring Boot! 1 on myboot-7cbfbd9b89-dl2hv
----

== Secret 생성하기

앞에서는 데이터베이스 연결 문자열(`user=MyUserName;password=pass:[*****]`)을 저장하는 데 ``ConfigMap``을 사용했습니다. 이번에는 이 민감한 데이터를 저장할 secret을 생성해 봅시다.

`kubectl` CLI는 데이터베이스 로그인처럼 일반적인(또는 `opaque`) secret을 생성하는 기능을 어느 정도 지원합니다.

[#create-secret-cli-secrets]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
kubectl create secret generic mysecret --from-literal=user='MyUserName' --from-literal=password='mypassword'
----

[#get-secret-cli-secrets]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
kubectl get secrets
----

그러면 다음과 비슷한 출력을 얻게 됩니다. OpenShift는 빌드나 배포에 필요한 서비스 계정 토큰 같은 Secret을 기본적으로 여러 개 만들어 두므로, 방금 만든 `mysecret` 외에도 낯선 이름들이 함께 보일 것입니다:

[.console-output]
[source,bash]
----
NAME                       TYPE                                  DATA   AGE
builder-dockercfg-96ml5    kubernetes.io/dockercfg               1      3d6h
builder-token-h5g82        kubernetes.io/service-account-token   4      3d6h
builder-token-vqjqz        kubernetes.io/service-account-token   4      3d6h
default-dockercfg-bsnjr    kubernetes.io/dockercfg               1      3d6h
default-token-bl77s        kubernetes.io/service-account-token   4      3d6h
default-token-vlzsl        kubernetes.io/service-account-token   4      3d6h
deployer-dockercfg-k6npn   kubernetes.io/dockercfg               1      3d6h
deployer-token-4hb78       kubernetes.io/service-account-token   4      3d6h
deployer-token-vvh6r       kubernetes.io/service-account-token   4      3d6h
mysecret                   Opaque                                2      5s
----

이것은 ``ConfigMap``이 아니라 ``Secret``이기 때문에, user와 password 값이 바로 보이지 않습니다:

[#describe-secret-cli-secrets]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
kubectl describe secret mysecret
----

[.console-output]
[source,bash]
----
Name:         mysecret
Namespace:    myspace
Labels:       <none>
Annotations:  <none>

Type:  Opaque

Data
====
password:  10 bytes
user:      10 bytes
----

[#get-secret-cli-yaml-secrets]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
kubectl get secret mysecret -o yaml
----


[source,yaml]
----
apiVersion: v1
data:
  password: bXlwYXNzd29yZA==
  user: TXlVc2VyTmFtZQ==
kind: Secret
metadata:
  creationTimestamp: "2020-03-31T20:19:26Z"
  name: mysecret
  namespace: myspace
  resourceVersion: "4944690"
  selfLink: /api/v1/namespaces/myspace/secrets/mysecret
  uid: e8c5f12e-bd71-4d6b-8d8c-7af9ed6439f8
type: Opaque
----

위의 password 필드 값이 base64로 인코딩되어 있다는 것을 확인하기 위해 이 값을 아래 echo 명령에 복사해 넣습니다.

[#get-secret-cli-password-secrets]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
echo 'bXlwYXNzd29yZA==' | base64 --decode
----

[.console-output]
[source,bash]
----
mypassword
----

[TIP]
====
시간이 부족하다면 대신 다음 명령을 실행할 수 있습니다.

[.console-input]
[source,bash,subs="+macros,+attributes"]
----
B64_PASSWORD=$(kubectl get secret mysecret -o jsonpath='{.data.password}')
echo "password:$B64_PASSWORD is decoded as $(echo $B64_PASSWORD | base64 --decode)"
----

====

그런 다음 사용자 이름에 대해서도 똑같이 해 봅니다.

[#get-secret-cli-username-secrets]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
echo 'TXlVc2VyTmFtZQ==' | base64 --decode
----

[.console-output]
[source,bash]
----
MyUserName
----

[TIP]
====
시간이 부족하다면 대신 다음 명령을 실행할 수 있습니다.

[.console-input]
[source,bash,subs="+macros,+attributes"]
----
B64_DATA=$(kubectl get secret mysecret -o jsonpath='{.data.user}')
echo "username:$B64_DATA is decoded as $(echo $B64_DATA | base64 --decode)"
----

====


또는 ``kubectl``을 사용해서 값을 가져올 수도 있습니다:

[#get-secret-kubectl-password-secrets]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
kubectl get secret mysecret -o jsonpath='{.data.password}' | base64 --decode 
----

== Secret 사용하기

:quick-open-file: myboot-deployment-configuration-secret.yml

방금 만든 secret을 사용하는 deployment인 ``{quick-open-file}``을 살펴봅시다.

include::partial$tip_vscode_quick_open.adoc[]

[.console-output]
[source,yaml,subs="+macros,+attributes"]
.{quick-open-file}
----
include::example$myboot-deployment-configuration-secret.yml[]
----
<.> 이 부분은 pod가 secret을 어디에서 찾을지 결정합니다. pod 안의 `/mystuff/secretstuff` 디렉터리에 있는 파일 형태로 제공됩니다.
<.> 이 부분은 ``mysecretvolume``이 실제로 무엇을 마운트해야 하는지 정의합니다. 여기서는 위에서 방금 만든 secret인 ``mysecret``입니다.

deployment(pod)가 secret을 사용할 수 있게 하는 한 가지 방법은 Volume Mount를 통해 제공하는 것입니다:

[source, yaml]
----
        volumeMounts:          
          - name: mysecretvolume
            mountPath: /mystuff/mysecretvolume
----

이 볼륨을 사용하도록 deployment를 업데이트해 봅시다:

[#replace-myboot-secrets]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
kubectl replace -f apps/kubefiles/myboot-deployment-configuration-secret.yml
----

__deployment가 업데이트되고 나면__, 새로 생성된 Pod에 exec로 접속합니다:

[#print-secrets-volume-secrets]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
PODNAME=$(kubectl get pod -l app=myboot --field-selector pass:['status.phase!=Terminating'] -o name)
kubectl exec $PODNAME -- ls -l /mystuff/secretstuff
kubectl exec $PODNAME -- cat /mystuff/secretstuff/password
----

결과:

[.console-output]
[source,bash]
----
total 0
lrwxrwxrwx. 1 root root 15 Jul 19 03:37 password -> ..data/password #<.>
lrwxrwxrwx. 1 root root 11 Jul 19 03:37 user -> ..data/user
mypassword #<.>
----
<.> secret 정의를 다시 떠올려 보세요. secret의 `.data` 섹션 아래에 있는 각 필드가 마운트된 secret을 나타내는 이 디렉터리 안의 파일이 되었습니다.
<.> `password` 파일의 내용을 ``cat``으로 확인하면 위에서 정의한 ``secret``의 `.data.password` 필드 값을 확인할 수 있습니다.

[TIP]
====
또는 다음 명령을 실행해서 pod에 rsh로 접속해 직접 둘러볼 수도 있습니다.

[.console-input]
[source,bash,subs="+macros,+attributes"]
----
PODNAME=$(kubectl get pod -l app=myboot --field-selector pass:['status.phase!=Terminating'] -o name)
kubectl exec -it $PODNAME -- /bin/bash
----
====


그런데 애플리케이션은 이 디렉터리에서 자격 증명을 찾아야 한다는 것을 어떻게 알까요? 애플리케이션(또는 properties)에 하드코딩할 수도 있지만, 환경 변수를 통해 `/mystuff/mysecretvolume` 경로를 pod에 제공해서 애플리케이션이 어디를 찾아야 할지 알게 할 수도 있습니다.

[TIP]
====
secret을 환경 변수로 직접 노출하는 것도 가능하지만, 이는 이 튜토리얼의 범위를 벗어납니다.
====

secret에 대해 더 자세히 알아보려면 https://kubernetes.io/docs/concepts/configuration/secret/[여기]를 참고하세요.

== 정리

[.console-input]
[source,bash]
----
kubectl delete deployment myboot
kubectl delete service myboot
----



